name: llama-3.2-reasoning-webgpu
type: gradio-space
sdk: static

metadata:
  space_id: Chris4K/llama-3.2-reasoning-webgpu
  original_url: https://huggingface.co/spaces/Chris4K/llama-3.2-reasoning-webgpu

deploy:
  targets:
    - public-repo
    - huggingface

build:
  command: bash build.sh

test:
  command: echo "Tests not yet implemented"

# Updated: 2026-01-03 13:26:18
